import React from "react";
import { GlobalContextProvider } from "./Context/store";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "React Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,300,0,0"
        />
      </head>
      <body>
        <GlobalContextProvider>
        <Header />
          <div className={inter.className}>{children}</div>
          
        </GlobalContextProvider>
          <Footer />
      </body>
    </html>
  );
}
